### PR TITLE
Run Transforms Via Redis Queue

### PR DESCRIPTION
**Pull request by odscjames**
https://crm.open-contracting.org/issues/5444

### CODE REVIEW

**Comment by jpmckinney** [comment]
Has this been thought through? My understanding is:

* When the source collection is done, it pushes a message to the queue.
* This worker will dequeue the message, find an upgrade collection, and work on it (unless it's already done). Meanwhile, we have a transform-collections work that runs every 3 hours, and it'll also work on the upgrade collection (unless it's already done). So we'll do the work twice.
* Then, same scenario: When the upgrade collection is done, it pushes a message to the queue. This worker will dequeue the message, find a compile collection, and work on it…

Through #232 I'm working on a proper queuing architecture where:

1. A file is added to the storage queue to be stored (by the API or Scrapy itself).
1. Once stored, the storage worker adds the file to the upgrade queue (if the collection is configured to do so).
1. Once the source collection is done, it closes itself. This cascades to the upgrade collection closing itself, which then adds itself to the compile queue.

This architecture also eliminates the present inefficiency where the current workers take a long time just to determine what work there is to do.

**Comment by odscjames** [comment]
Just seen comment when doing other work, sorry.

Yes, it's possible that work may be looked at twice. But both transforms check if work is already done and won't redo work, so it's not terrible - but I agree it's not the best. Basically we were trying to do small things and not do a large scale change.

Also, moving to a more granular system will be good, but one of the transforms can't start until it's source collection is finished, so there will need to be some reference to the collection object.

**Comment by jpmckinney** [comment]
Yes, the new code would use a scatter/gather or similar pattern.

**Comment by jpmckinney** [comment]
Got a first exception due to this: https://sentry.io/organizations/open-contracting-partnership/issues/1630536966/

**Pull request merged**
