### PR TITLE
Delete the collection and its notes after all its data is deleted

### LINKED ISSUE #243: Is there a use case for deleting a source collection, but keeping its transforms?
Following from https://github.com/open-contracting/kingfisher-process/issues/141#issuecomment-517288985

Having the concept of a 'deleted collection' adds complexity, because many queries, commands, operations, etc. will have to be aware of the concept (mainly to exclude deleted collections from consideration), including queries run by helpdesk analysts.

(*Update for clarification:* We need the concept of a 'collection marked for deletion', because deleting a collection can take some time. However, once the collection is indeed deleted, should we delete the row from the `collection` table as well?)

The only good reason I can think of to not just delete collections from the database entirely is if it's a source collection with (non-deleted) transformed collections. In such a case, it's useful to keep the notes, errors and warnings from the source collection, to understand the transformed collections' provenance.

However, **is there ever a case where we want to delete the source collection, but keep the transforms?** I can see there could be a niche use case to save disk space eventually, but I think we can consider other alternatives that don't add as much complexity.

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #243

### CODE REVIEW

**Comment by odscjames** [comment]
This will fail with Transforms; if Collection A is raw data, and collection B is a transform from A that has finished then collection A will say it's possible to delete. But it will fail as the row for collection B will have a foreign key reference to it.

**Comment by jpmckinney** [comment]
[Review Kingfisher Process PRs](https://trello.com/c/UNsZ27w5/170-review-kingfisher-process-prs)

**Comment by jpmckinney** [comment]
Good catch! I added a commit to set the foreign key to NULL. The delete-collection command already protects against marking a source collection for deletion if it still has non-deleted, incomplete transformed collections – so there should be no harm to setting it to NULL.

**Comment by odscjames** [comment]
Had to add a commit to stop transform process crashing. I'll let you approve that part and merge, if we want to do this.

I'd ask if it's worth a code change like this at this point;

A) This means in view component, we'll have to adopt a principle of "no foreign keys to collection ID's". We don't use any of these currently, but we'll have to make sure we don't in future. (Tho maybe that's a good thing anyway)

B) Notes will be lost; a note will be attached to the source collection only so if someone deletes a source collection and leaves the destination collection the note will be deleted and lost. In the current system, you can always work back and see the original notes

**Comment by jpmckinney** [comment]
A) Sounds like a good principle. In general, I don't think Views should assume that any data in the `public` schema will remain available.

B) Per discussion in #253, there's no use case for deleting source collections but keeping its transformed collections – so it's okay for all the notes to go away.

**Pull request merged**
