### PR TITLE
Use multiple threads to do transform-collections.

### PR DESCRIPTION
**Pull request by kindly**

### CODE REVIEW

**Comment by robredpath** [comment]
[kf-process: Make transforms run more quickly to help Helpdesk get things done!](https://trello.com/c/EMpgyJU8/192-kf-process-make-transforms-run-more-quickly-to-help-helpdesk-get-things-done)

**Comment by jpmckinney** [comment]
I won't review as WIP, but I noticed duplicate `print()` lines, a removed logger line, an unused `logger` variable while checking the general direction (which looks good as an intermediate solution).

**Comment by odscjames** [comment]
After this is deployed, need to edit salt to add ` --threads 10` or something

**Comment by odscjames** [comment]
@kindly has checked my commit, so approving and pushing out

**Pull request merged**
