### PR TITLE
Add indexes to foreign keys

### LINKED ISSUE #237: Add indices to all foreign keys
Not all foreign keys have indexes (SQLAlchemy doesn’t add them but default).

If necessary, we can [build indexes concurrently](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY).

The new indices would correspond to (replacing `<name>`):

        CREATE INDEX <name> ON public.collection USING btree (transform_from_collection_id);
        CREATE INDEX <name> ON public.collection_file USING btree (collection_id);
        CREATE INDEX <name> ON public.collection_file_item USING btree (collection_file_id);
        CREATE INDEX <name> ON public.collection_note USING btree (collection_id);
        CREATE INDEX <name> ON public.record USING btree (package_data_id);
        CREATE INDEX <name> ON public.record_check USING btree (record_id);
        CREATE INDEX <name> ON public.record_check_error USING btree (record_id);
        CREATE INDEX <name> ON public.release USING btree (package_data_id);
        CREATE INDEX <name> ON public.release_check USING btree (release_id);
        CREATE INDEX <name> ON public.release_check_error USING btree (release_id);

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #237 

This will improve the performance of some queries run by the CLI commands (and the indexes are also relevant to any future refactorings of those).

### CODE REVIEW

**Comment by odscjames** [comment]
Note we do have indexes in the table definitions in https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/database.py#L131 - we may want to add them there to, or take them out of database - we should be consistent, or at least put a comment in as to why we aren't being consistent. I don't know they do anything except provide a handy reference.

**Comment by odscjames** [comment]
Note this pull request and #249 conflict - note they both have 

     down_revision = '53699ddc9872' 

In the alembic migration. (I don't know why Alembic does it this way, for exactly the reason of this problem). Whichever one we want to merge in first, the other needs fixing: https://stackoverflow.com/questions/22342643/alembic-revision-multiple-heads-due-branching-error/51456404#51456404

**Comment by jpmckinney** [comment]
I've added the indexes to database.py. Let's merge this first. I'll fix the other PR.

**Comment by jpmckinney** [comment]
I'll deploy this now, to avoid having lots of migrations to run at once with the other PRs.

**Comment by jpmckinney** [comment]
Since Scrapy is still running, I'll do manual steps, which I'll document at https://ocdsdeploy.readthedocs.io/en/latest/how-to/index.html

**Comment by jpmckinney** [comment]
Deployed. It only took a few minutes to migrate, which is good news for other migrations.

**Pull request merged**
