### PR TITLE
OCDS Kingfisher Process - first commit.

### PR DESCRIPTION
**Pull request by odscjames**
A lot of this code was taken from older versions of https://github.com/open-contracting/kingfisher and is by many people.

### CODE REVIEW

**Comment by odscjames** [comment]
Hello @kindly - Your back from holiday one day before me so I thought I'd leave this for you :-)

I'm not saying this is perfect or done in any way - there are already discussions that might lead to bits being changed. But I thought it was better to get things on master and get us doing real P.R.'s sooner rather than later, or - If I've done something you object to - I thought it was better to start that discussion sooner rather than later :-)

Hope your holiday was good!

**Comment by jpmckinney** [comment]
Is there any code outside the web/ folder that is new or significantly different from before? Same question for non-code (e.g. documentation), besides `web-api-v1.rst`.

**Comment by odscjames** [comment]
Not really. A lot of code has been moved about and the edges of where functions/classes are have moved in some cases, but most of the actual lines of code are like before. It does have the item thing we discussed in https://github.com/open-contracting/kingfisher/issues/271 - I'm not saying it definitely will be there in the long run, but I had already added it while I was prototyping functionality (it didn't take long) so it's there for now till we discuss it more. I also took the opportunity of a clean start to clean up the names and locations of some config vars so they were consistent - the docs reflect that. Also some general code tidyup we had already started; for instance now almost all the config stuff is loaded in one place (the Config class) rather than several.

**Comment by jpmckinney** [comment]
Great, thanks! All sounds good to me.

**Pull request merged**
