### PR TITLE
Relax requirements.in versions, to allow patch-level security updates.

### PR DESCRIPTION
**Pull request by jpmckinney**
Also:

- Remove libcove, as it is not a direct dependency, and as it is already required by libcoveocds.
- Sort packages.

### CODE REVIEW

**Comment by odscjames** [comment]
Can we just hold this a few days while we do https://github.com/open-contracting/kingfisher-process/issues/201 ? When requirements.in changes, we need to update requirements.txt too - this ensures Travis tests it properly, and that any future commits are clear as to why a change is happening. However we realise this isn't fully documented yet, and we will do that as part of that issue.

**Comment by jpmckinney** [comment]
There's no rush, but I don't think this causes any change to `requirements.txt` (libcoveocds will install libcove even if it's not declared in `requirements.in`). The output of `pip freeze` is the same before and after.

**Comment by odscjames** [comment]
[Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by odscjames** [comment]
@rhiaro and I just checked this, and in fact the contents of requirements.txt do change.

1) The order is different, because of the reordering in this pull request. It's really helpful to be able to look at a pull request and make sure there have been no major upgrades in the locked libraries. When they are re-ordered it's more difficult to compare easily, so it's better to do that in this pull request and not surprise the next person who updates.

2) There are minor upgrades that come in; for instance commonmark==0.9.0 goes to
commonmark==0.9.1

The above we should be able to fix easily with a run of the upgrade script, however when libcove is removed from requirements.in (as you say, it should not be needed here) then jsonschema==2.6.0 suddenly jumps to jsonschema==3.1.1. If we put libcove back in requirements.in then it stays at 2.6.0. It's the end of the day here, but we would like to look into why this is happening, and also double check that the upgrade to 3.1.1 would not cause any problems.

**Comment by odscjames** [comment]
> then jsonschema==2.6.0 suddenly jumps to jsonschema==3.1.1. If we put libcove back in requirements.in then it stays at 2.6.0. 

I have not been able to recreate that, so I'm not sure what was happening there.

I also note that https://travis-ci.org/OpenDataServices/lib-cove/builds/602394964 ran with JSONSchema 3, so that's a good test. Oddly,  https://travis-ci.org/open-contracting/lib-cove-ocds/builds/598185080 runs with JSONSchema 2 - this is explained in https://github.com/open-contracting/lib-cove-ocds/issues/35

I have rebased the branch and added an extra commit with the new lock files. @rhiaro can you review?

**Comment by jpmckinney** [comment]
I'd really like to stop seeing Sentry errors for a fix I made to OCDS Kit a month ago (can't be good for the analysts whose data isn't getting upgraded…), so I put this PR together with another commit to upgrade OCDS Kit. The new PR keeps packages in the original order to keep the diff small. We can sort packages in its own PR.

**Comment by jpmckinney** [comment]
See #212

**Pull request closed without merging**
