### PR TITLE
WIP: transform: Compile Releases Transform - include records table & options for behaviour

### PR DESCRIPTION
**Pull request by odscjames**
Options for behaviour around what to do with existing compiled releases it finds

https://github.com/open-contracting/kingfisher-process/issues/63

### CODE REVIEW

**Comment by odscjames** [comment]
@jpmckinney Can you confirm the new options column here matches what you are building towards?

**Comment by odscjames** [comment]
[Process: Add support for records to compile-release transform](https://trello.com/c/ZjcZkv3C/191-process-add-support-for-records-to-compile-release-transform)

**Comment by jpmckinney** [comment]
Yes, the column would match the Django configuration.

I don't think we need two boolean flags to control the behavior of the 'transform-use-existing-compiled-releases' option, though.

**Comment by odscjames** [comment]
> Yes, the column would match the Django configuration.

Thanks

> I don't think we need two boolean flags to control the behaviour of the 'transform-use-existing-compiled-releases' boolean, though.

As this will all be changing at some point soon anyway I was not treating this detail with the same importance. I'll focus on the actual transform now, but we can do this after if you want.

**Comment by odscjames** [comment]
temp on hold, see issue

**Comment by odscjames** [comment]
closing, we are doing without options now

**Comment by odscjames** [comment]
see #278 instead

**Pull request closed without merging**
