### PR TITLE
Move dependencies back into req files, fix setup.py for use by views,…

### LINKED ISSUE #195: update_requirements, and thus frozen requirements system is broken
When the script is run now, the following line appears in requirements_dev.txt and requirements.txt

    -e git+git@github.com:open-contracting/kingfisher-process.git@cd1d383bce6f21c156d52c1044c254719cf57d5a#egg=ocdskingfisher

This breaks on Travis, as the Travis process is not set up with a user that can SSH into GitHub.

This will also break on our live deploy, as again a SSH user for GitHub isn't set up there.

And we can probably expect this to break on other users setups too.

We think commit https://github.com/open-contracting/kingfisher-process/commit/6552d309c66f520f427877735f5a19db923f039a caused this. The change to  "-e ." may be causing this bad line to appear. 

(Note, this error only appeared when we tried to update requirements.txt, which explains why Travis worked till now.)

We need to test further and then suggest fixes.

### PR DESCRIPTION
**Pull request by rhiaro**
… fixes #195

Tested with kingfisher-views on a test branch that uses this commit to install kf-process: https://travis-ci.org/open-contracting/kingfisher-views/builds/593583714

### CODE REVIEW

**Comment by odscjames** [comment]
How did ocdsextensionregistry get in req.txt?

I think the rest looks good.

This has the locking files back in for deploys, and for dev's work, which makes for consistent installs and less surprises.

The update requriements script can be set up somewhere else - we will make sure how to use the requirements files is documented well for short term use. (And we can discuss other ways of locking dep's for the long term)

**Comment by odscjames** [comment]
Have worked out ocdsextensionregistry problem in direct chat, another commit incoming

**Comment by jpmckinney** [comment]
Can we delete setup.py?

**Comment by rhiaro** [comment]
Can't delete setup.py until https://github.com/open-contracting/kingfisher-views/issues/34 is fixed as far as I know

**Comment by odscjames** [comment]
I think @rhiaro is right on that.

Rest looks good now, thanks!

**Comment by jpmckinney** [comment]
Ah, okay, I thought we’d do that first, but I guess the order isn’t important.

**Pull request merged**
