### PR TITLE
Add collection id to release, record, compiled_release

### LINKED ISSUE #236: Add collection_id to release, record, compiled_release (instead of using views)
Since we only insert and don't update most tables, we won't have the usual downsides to denormalization.

The new collection_id column should have an index. Note the performance of the views (without an index):

```sql
EXPLAIN ANALYZE SELECT * FROM release_with_collection WHERE collection_id = 800;
```

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Gather  (cost=1613330.92..4072300.22 rows=25972 width=69) (actual time=8.118..12.213 rows=0 loops=1)
   Workers Planned: 4
   Workers Launched: 4
   ->  Parallel Hash Join  (cost=1612330.92..4068703.02 rows=6493 width=69) (actual time=0.230..0.231 rows=0 loops=5)
         Hash Cond: (release.collection_file_item_id = collection_file_item.id)
         ->  Parallel Seq Scan on release  (cost=0.00..2317749.09 rows=36961809 width=65) (never executed)
         ->  Parallel Hash  (cost=1612272.79..1612272.79 rows=4650 width=8) (actual time=0.030..0.030 rows=0 loops=5)
               Buckets: 32768  Batches: 1  Memory Usage: 0kB
               ->  Parallel Hash Join  (cost=39248.79..1612272.79 rows=4650 width=8) (actual time=0.063..0.065 rows=0 loops=1)
                     Hash Cond: (collection_file_item.collection_file_id = collection_file.id)
                     ->  Parallel Seq Scan on collection_file_item  (cost=0.00..1503531.88 rows=26473188 width=8) (never executed)
                     ->  Parallel Hash  (cost=39170.17..39170.17 rows=6290 width=8) (actual time=0.014..0.015 rows=0 loops=1)
                           Buckets: 16384  Batches: 1  Memory Usage: 0kB
                           ->  Parallel Index Scan using unique_collection_file_identifiers on collection_file  (cost=0.69..39170.17 rows=6290 width=8) (actual time=0.014..0.014 rows=0 loops=1)
                                 Index Cond: (collection_id = 800)
 Planning Time: 0.428 ms
 Execution Time: 12.254 ms
```

Compare that to a table using an index:

```sql
EXPLAIN ANALYZE SELECT * FROM release WHERE collection_file_item_id = 106127340;
```

```
                                                                     QUERY PLAN                                                                     
----------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using release_collection_file_item_id_idx on release  (cost=0.57..1431.45 rows=3339 width=65) (actual time=0.017..0.017 rows=0 loops=1)
   Index Cond: (collection_file_item_id = 106127340)
 Planning Time: 0.067 ms
 Execution Time: 0.028 ms
```

For backwards-compatibility with existing notebooks, I propose moving the one-time creation of the old views to kingfisher-views (though keeping them in the `public` schema).

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #236

### CODE REVIEW

**Comment by jpmckinney** [comment]
[Review Kingfisher Process PRs](https://trello.com/c/UNsZ27w5/170-review-kingfisher-process-prs)

**Comment by odscjames** [comment]
Note I would expect the deploy on this to take a number of minutes, and during that time any store operations will I think fail (trying to write data to a column that won't exist until the transaction is finished), so we should deploy with warning probably.

**Comment by odscjames** [comment]
I'll leave you to check additional commit I added.

Document for notice says 72hr or 24 hrs notice (Now I read it, it's not clear when to use which?). So I guess 3 emails:

1) "In a few days we will be adding a new feature, but you will be unable to start any scrapes for an hour or so, there will be emails at the time."

2) Make sure no scrapes are running currently, send "Please don't start any scrapes". Deploy.

3) When done, send "You can now run scrapes again, BTW you can stop using the *_with_collection views!"

If your happy with addition I can start process. We should save merging till just before we deploy, in-case we need to merge and deploy any urgent fix in the meantime.

**Comment by jpmckinney** [comment]
Commit is good, thanks!

I don't think this meets the criteria for 'major downtime', so we can start now / anytime that scrapers aren't presently running. I added some notes about what is considered disruptive.

**Comment by odscjames** [comment]
Ok, I'll just do emails 2 and 3 then and start very shortly.

**Comment by jpmckinney** [comment]
FYI, I logged in as root and ran:

```
sudo -u postgres psql postgres -c 'SELECT pid, state, wait_event_type, NOW() - query_start, query FROM pg_stat_activity;'
```

The migration is currently running `UPDATE release …` (which it started 11 hours ago). So, the record update already ran, and `UPDATE compiled_release …` is the only remaining slow query.

**Comment by jpmckinney** [comment]
Hmm, the migration seems to have failed, though I don't know where it was running from. @odscjames Do you have any error output?

To retry, I can run it manually following [these steps](https://ocdsdeploy.readthedocs.io/en/latest/how-to/kingfisher.html#deploy-kingfisher-process-without-losing-scrapy-requests).

**Comment by odscjames** [comment]
I stopped it. I was watching it and it clearly wasn't going to finish in a reasonable or predictable time (my estimation was linear, based on how long records took, and was clearly wrong) , and compiled_release had almost as many rows to run as release to work through.

We will do a urgent pull request to do a straight revert, so master is again deployable.

We can then retry by rolling it out in stages, with no more than the usual downtime of a few minutes, using the standard database migration technique for situations like this - I will post more on that shortly.

**Comment by odscjames** [comment]
I still have the deploy token, and will keep it until I can return the sever to a stable known state - please don't do any actions on the server until then.

Briefly, the procedure is to make sure the code can work with the new and old database structures, and then do the long-running database migration in the background while others work, then remove that special code.

1) Deploy adding columns, NULLABLE, and indexes
2) Deploy changes to Store so any new data written fills this column.
3) Manually run SQL to fill existing rows with data.
4) Deploy changes to make it NOT NULL.
5) Finally, deploy changes to read from the table and not the now-deprecated view.

This will require no downtime notices and no special downtime (beyond the usual "make sure no spiders are running when you deploy")

**Comment by odscjames** [comment]
Master rolled back, deploy done on server and deploy token returned.

**Pull request merged**
