### PR TITLE
Make some fields non-nullable

### PR DESCRIPTION
**Pull request by jpmckinney**
#235

### CODE REVIEW

**Comment by odscjames** [comment]
Note this pull request and #248 conflict - note they both have 

     down_revision = '53699ddc9872' 

In the alembic migration. (I don't know why Alembic does it this way, for exactly the reason of this problem). Whichever one we want to merge in first, the other needs fixing: https://stackoverflow.com/questions/22342643/alembic-revision-multiple-heads-due-branching-error/51456404#51456404

**Comment by odscjames** [comment]
Note bits were left out of this pull request - see https://github.com/open-contracting/kingfisher-process/issues/235#issuecomment-566849348 - Personally I'd rather that issue was resolved and we do these all at once.

**Comment by odscjames** [comment]
This looks fine, tho this changes behaviour so passing 2 empty filename's in the same collection now raises an error. Given we know we have code that might do this, I'd like to sort that before changing this behaviour: further discussion in https://github.com/open-contracting/kingfisher-process/issues/47#issuecomment-566994963

**Comment by jpmckinney** [comment]
I've done everything except #47, which I think needs a fix in scrape, and shouldn't be a blocker for process. This should be merged after #248 due to alembic revision IDs.

**Comment by jpmckinney** [comment]
Forgot that I had to merge #248 into this, so that alembic can run and tests can pass.

**Comment by jpmckinney** [comment]
[Review Kingfisher Process PRs](https://trello.com/c/UNsZ27w5/170-review-kingfisher-process-prs)

**Comment by odscjames** [comment]
#248 has now been merged, and I think given the order of branches that have come off other branches this should be the next pull request we prioritise - is that right?

It's slightly confusing that this pull request shows code changes that are already in master - would a rebase and squash help create a clearer pull request?

**Comment by jpmckinney** [comment]
Yes, this is the next one (the PR numbers are in order).

I've merged with master, so the diff should be smaller.

**Pull request merged**
