### PR TITLE
Reduce CoVE output

### PR DESCRIPTION
**Pull request by jpmckinney**
#269

### CODE REVIEW

**Comment by jpmckinney** [comment]
[Kingfisher: Store a subset of the CoVE output](https://trello.com/c/lB1DhTHf/221-kingfisher-store-a-subset-of-the-cove-output)

**Comment by jpmckinney** [comment]
After merge and deploy, I'm guessing the DB will auto-vacuum. If not, we should do so manually. Once that's done, we can check disk usage. If still high, I can work with analysts to schedule collections for deletion in CRM 5533.

**Comment by kindly** [comment]
@jpmckinney 

In principle this looks good.  My only concern is how long it will take to do the update as the table is so large (~134 million rows).  Everything will be in one transaction and it will be really hard to tell if it will ever complete and may block the table while doing it.  My estimate is it will take at least days to run perhaps over a week.

https://blog.codacy.com/how-to-update-large-tables-in-postgresql/ gives a summary of other options.  We went with the first one another time but it has the issue of needing to write some custom code and that should probably live outside a migration and be a one off.  The other options mean you need to copy the data we barely have space to do that.

However, I think the migration in this pull request is fine and will be good for smaller databases.

**Comment by jpmckinney** [comment]
Why so long? I'd expect it to be pretty fast. It's not doing any JOINs or WHEREs – just going through every row and doing a simple JSON key deletion.

I think we can try merging and deploying this PR as-is. If it turns out to be slow (easy to monitor), we can split out the migration, similar to the much more complicated deployment of https://github.com/open-contracting/kingfisher-process/issues/236#issuecomment-572451327

**Comment by kindly** [comment]
@jpmckinney happy to try, hope I am wrong about how long it will take but will not do much harm to try.
I have not got root access to server so will not be able to deploy unless it is given to me.

**Comment by jpmckinney** [comment]
Thanks, @kindly. I'll deploy now and see what happens. Happy to restore root access, but as you hadn't deployed to this server in six months (according to deploy token log), I figured it'd be a good policy to remove access until needed.

**Comment by jpmckinney** [comment]
We can check what queries are running with:

```sql
SELECT pid, state, NOW() - query_start as time, wait_event_type, query FROM pg_stat_activity WHERE query <> '' ORDER BY time desc;
```

We used to run Views on the entire DB nightly, so I think it shouldn't take too long. We'll see!

**Comment by jpmckinney** [comment]
The release_check query recently completed, so after about 12h. Should be less than 12h for the record_check query.

**Comment by jpmckinney** [comment]
The salt-ssh command terminated with:

```
[ERROR   ] JSON Render failed for: 
client_loop: send disconnect: Broken pipe
[ERROR   ] Expecting value: line 1 column 1 (char 0)
kingfisher-process1:
```

I assume because the SSH connection has held open too long. I might need to redeploy once the current query finishes, in which case I might want to add:

```sql
WHERE cove_output ? 'releases_aggregates'
```

to the migration

**Comment by jpmckinney** [comment]
The record_check query seems to have completed a couple hours ago, based on Prometheus graphs, so after about 5 hours.

autovacuum is now running on release_check, record_check, and toast.

**Comment by jpmckinney** [comment]
By the way, the server has an SSD, so random access is not a significant performance concern.

**Comment by jpmckinney** [comment]
Ran VACUUM FULL on release_check and we recovered 1TB 🎉

**Pull request merged**
