### PR TITLE
Relax requirements.in versions, and update ocdskit

### PR DESCRIPTION
**Pull request by jpmckinney**
I added a new issue to add the tests @rhiaro mentioned in Trello. #213

Given that I wrote OCDS Kit (so I know what the change needs to be), and given that the lack of tests haven't been a blocker so far, I think we can merge this without new tests.

### CODE REVIEW

**Comment by odscjames** [comment]
[Kingfisher-Process: Upgrade to OCDS Kit 0.1.1](https://trello.com/c/vohMXCYj/106-kingfisher-process-upgrade-to-ocds-kit-011)

**Comment by odscjames** [comment]
Depolyed

**Comment by jpmckinney** [comment]
Hmm, if I activate the venv and pip freeze, I still see 'ocdskit==0.0.5'

**Comment by jpmckinney** [comment]
Ah, somehow requirements.txt has 0.0.5, though I ran the update_requirements.sh script.

**Pull request merged**
