### PR TITLE
Add collection_id to release, record, compiled_release - Stage 5

### PR DESCRIPTION
**Pull request by odscjames**
Don't use views any more, use raw tables

https://github.com/open-contracting/kingfisher-process/issues/236

### CODE REVIEW

**Comment by jpmckinney** [comment]
Can we add https://github.com/open-contracting/kingfisher-process/commit/705169d40a4bd7ec4e8ad5986ddebed29f42613c to this PR?

**Comment by odscjames** [comment]
We did it again - I was working on docs when you commented. I actually did something different tho.

**Comment by odscjames** [comment]
Updating the diagram also includes earlier changes to structure.

**Comment by odscjames** [comment]
Ready for review

**Comment by odscjames** [comment]
[Review Kingfisher Process PRs](https://trello.com/c/UNsZ27w5/170-review-kingfisher-process-prs)

**Pull request merged**
